### ISSUE TITLE
Button doesn't show up

### ISSUE THREAD

**Issue by bob448** [neves768/robloxserverfinder#2]
Roblox's new play button change might be the problem.

**Comment by neves768** [comment]
Hey bob448, thanks for your bug report. I'll look for that new button today. There also should be some changes to speed up prediction for games with >50k simultaneously

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
From: bob448 ***@***.***>
Sent: Sunday, May 30, 2021 1:33:24 PM
To: neves768/robloxserverfinder ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neves768/robloxserverfinder] Button doesn't show up (#2)


Roblox's new play button change might be the problem.
